config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :users
  
  get 'tweets/index'
  resources :tweets
  
  root 'top#main'
  get 'top/login_form'
  post 'top/login'
  get 'top/logout'
  
  resources :likes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes, dependent: :destroy #ツイートを消すといいねも消える
    has_many :like_users, through: :likes, source: :user
    
    def like(user)
        likes.create(user_id: user.id)
    end
      
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
      
    def liked?(user)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :tweets, dependent: :destroy #ユーザを消すとツイートも消える
    has_many :likes, dependent: :destroy #ユーザを消すといいねも消える
    has_many :like_tweets, through: :likes, source: :tweet
    
    validates :password, presence: true, confirmation: true
    
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    private
        def current_user
            if session[:login_uid]
            User.find_by(uid: session[:login_uid])
            end
        end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user)
           tweet.like(current_user)
        end
        #user = User.find_by(uid: session[:login_uid])
        #user.like_tweets << tweet
        redirect_to root_path
    end
    
    def destroy
        tweet = Tweet.find(params[:id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        #user = User.find_by(uid: session[:login_uid])
        #tweet.likes.find_by(user_id: user.id).destroy
        redirect_to root_path
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        @tweets = Tweet.all
        render 'main'
    end
    
    def login
        
        user = User.find_by(uid: params[:uid])
        
        if user
            
            if  BCrypt::Password.new(user.pass) == params[:pass]
                session[:login_uid]=params[:uid]
                session[:user_id] = user.id
                redirect_to '/'
            else
                flash[:alert] = '※ユーザIDかパスワードが間違ってるヨ！'
                redirect_to top_login_form_path
            end
        else
            flash[:alert] = '※ユーザIDかパスワードが間違ってるヨ！'
            redirect_to top_login_form_path
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to '/'
    end
    
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  
  def new
  end
  
  def create
    user_id = session[:user_id]
    
    tweet = Tweet.new(message: params[:message], tdate: Time.current, user_id: user_id)
    if tweet.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to root_path
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @users = User.all
  end
  
  def create
    if User.exists?(uid: params[:uid])
      flash[:alert] = '※そのユーザIDは使えんでぇ～'
      redirect_to new_user_path
    else
      #hashed_password = BCrypt::Password.create(params[:pass])
      user = User.new(uid: params[:uid], password: params[:password], password_confirmation: params[:password_confirmation])
      user.save
      redirect_to users_path
    end
  end
  
  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
    <% end %>
  </body>
</html>

app/views/top/login_form.html.erb
<%= form_tag '/top/login', method: :post, data:{turbo:false} do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

<p><%= link_to '戻る', root_path %></p>

app/views/top/main.html.erb
<h2>ツイート一覧</h2>

<table>
  <tr>
    <th>ツイート</th>
    <th>投稿ユーザー</th>
  </tr>
  <% @tweets.each do |tweet| %>
    <tr>
      <td>
          <%= tweet.message %>
      </td>
      <td>
          <% user = User.find(tweet.user_id) %>
          <%= user.uid %>
      </td>
      <td>
          <% if current_user %>
            
            <% if tweet.liked?(current_user) %>
              <%= link_to 'いいね削除', like_path(tweet), data: { turbo_method: :delete } %>
              
            <% else %>
              <%= link_to 'いいね', likes_path(tweet_id: tweet.id), data: { turbo_method: :post } %>
            <% end %>
            
          <% end %>
          <%= link_to '削除', "/tweets/#{tweet.id}", data: { turbo_method: :delete } %>
      </td>
    </tr>
  <% end %>
</table></br>

<% if current_user %>
    <!-- ログイン中の場合 -->
    
    <%= form_tag '/tweets', ({ action: :create }) do %>
      <%= label_tag :message, 'メッセージ' %>
      <%= text_field_tag :message %>
      <%= submit_tag 'ツイート' %>
    <% end %>

    <p><%= link_to 'ログアウトはここだよ～', top_logout_path %></p>

<% else %>
    <!-- ログインしていない場合 -->
    <p><%= link_to 'ログイン', top_login_form_path %></p>
<% end %>

<p><%= link_to 'ユーザの新規登録してね～', new_user_path %></p>

app/views/tweets/index.html.erb
<h2>ツイート一覧</h2>

<table>
  <tr>
    <th></th>
  </tr>
  <% @tweets.each do |tweet| %>
    <tr>
      <td>
          <%= tweet.message %>
          <%= tweet.user_id %>
          <%= link_to '削除', "/tweets/#{tweet.id}", data: { turbo_method: :delete } %>
      </td>
    </tr>
  <% end %>
</table>

<p><%= link_to '新規ツイートしてね～', new_tweet_path %></p>

<p><%= link_to 'ログアウトはここだよ～', top_logout_path %></p>

app/views/tweets/new.html.erb
<%= form_tag ({ action: :create }) do %>
    <%= label_tag :message, 'メッセージ' %>
    <%= text_field_tag :message %>
    <%= submit_tag '投稿' %>
<% end %>

<p><%= link_to '戻る', :back %></p>

app/views/users/index.html.erb
<h2>ユーザー一覧</h2>

<table>
  <tr>
    <th>ユーザー名</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td>
          <%= user.uid %>
          <%= link_to '削除', "/users/#{user.id}", data: { turbo_method: :delete } %>
      </td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to '新規登録してね～', new_user_path %>
  <%= link_to 'さっそくログインするべ！', top_login_form_path %>
  <%= link_to 'ツイート一覧を見る', root_path %>
</p>

app/views/users/new.html.erb
<%= form_tag ({ action: :create }) do %>
  <%= label_tag :uid, 'ユーザー名' %>
  <%= text_field_tag :uid %>
  <%= label_tag :password, 'パスワード' %>
  <%= password_field_tag :password %>
  <%= label_tag :password_confirmation, 'パスワード(確認)' %>
  <%= password_field_tag :password_confirmation %>
  <%= submit_tag '新規登録' %>
<% end %>

<h2>ユーザー一覧</h2>

<table>
  <tr>
    <th>ユーザー名</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td>
          <%= user.uid %>
          <%= link_to '削除', "/users/#{user.id}", data: { turbo_method: :delete } %>
      </td>
    </tr>
  <% end %>
</table></br>

<p><%= link_to '戻る', root_path %></p>